set nocompatible
set autoindent
set cindent
set smartindent
set wrap
set ruler
set ts=4 sw=4
set number
set expandtab
set hlsearch
set ignorecase
set paste
set ruler
set showmatch
set cursorline 
set linebreak
set background=dark
set history=1000

set colorcolumn=80

syntax on
filetype indent on
colorscheme desert

au Filetype python setl ts=2 sw=2 sts=2
au Filetype cpp setl ts=2 sw=2 sts=2
au! BufRead,BufNewFile *.gradle setfiletype groovy

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'rhysd/committia.vim'
call vundle#end()

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => Project Specific vimrc
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" allow project-specific vimrc files to be sourced
set exrc
" make sure project-specific vimrc files don't do unsafe things
set secure
