set nocompatible
set autoindent
set cindent
set smartindent
set wrap
set ruler
set ts=4 sw=4
set number
set expandtab
set hlsearch
set ignorecase
set paste
set ruler
set showmatch
set cursorline 
set linebreak
set background=dark
set history=1000

syntax on
filetype indent on
colorscheme desert

au! BufRead,BufNewFile *.gradle setfiletype groovy

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'
Plugin 'scrooloose/nerdtree'
call vundle#end()
